/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Materia;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author AsRock
 */
public class JIntlFrAltaDeMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIntlFrAltaDeMaterias
     */
    public JIntlFrAltaDeMaterias() {
        initComponents();
        jcbxAnioalQuePertenece.setSelectedIndex(-1);
        this.setLocation(10, 15);
    }
    
    //---Metodo limpiar Campos--------------------------------------------------
    private void limpiarCampos(){
            
        jtextCodigoDeMateria.setText("");
        jtextNombreDeLaMateria.setText("");
        jcbxAnioalQuePertenece.setSelectedIndex(-1);
        
    }
     //-------------------------------------------------------------------------
    
    private boolean chequearSiExisteEseCodigoDeMateria(int codigoMatriaParam){            //<---Este metodo lo llamo poara pasarle un codigo de materia y chequear si el mismo ya no esta almacenado
    
        ArrayList<Materia> materias  = Menu.getMaterias();
        boolean resultado = false;
        
        for(Materia materiaIt: materias){
        
            resultado = (codigoMatriaParam == materiaIt.getIdMateria());
        }
        
        
        return resultado;
    }
    //-------------------------------------------------------------------------
    
    private boolean chequearSiExisteEsaMateriadeEseAnio(String nombreMateriaParam, int anioAlQuePerteneceParam){            //<---Este metodo lo llamo para saber si esa materia, de ese año (que pertenece) ya esta almacenadas
    
        ArrayList<Materia> materias  = Menu.getMaterias();
        boolean resultado = false;
        
        for(Materia materiaIt: materias){
        
            resultado = (( materiaIt.getNombre().equals(nombreMateriaParam)) 
                        && (materiaIt.getAnio() == anioAlQuePerteneceParam));
        }
        
        
        return resultado;
    }
    //-------------------------------------------------------------------------
    
    private void registrarMateria (){

        //---Chequeo, antes, si hay campos sin completar--- 
        if (jtextCodigoDeMateria.getText().equals("") ||                                  
            jtextNombreDeLaMateria.getText().equals("") ||
            jcbxAnioalQuePertenece.getSelectedIndex() == -1 ){
            
            JOptionPane.showMessageDialog(this, "No pueden quedar campos sin completar!");  
  
        }else {
        
            //---Recupero los datops de los testField, le saco los espacios de los costados y los guardo en mayuscula (en nombreMateria)---
            int idMateria = Integer.parseInt(jtextCodigoDeMateria.getText());                       
            String nombreMateria = jtextNombreDeLaMateria.getText().trim().toUpperCase();
            int anioAlQuePertenece = (jcbxAnioalQuePertenece.getSelectedIndex() + 1 );
            
            //---Chequeo, si no esa materia, de ese año, esta almacenada con anteioridad---      
            if (chequearSiExisteEsaMateriadeEseAnio(nombreMateria,anioAlQuePertenece)){
            
                JOptionPane.showMessageDialog(this, "ATENCION !!! La Materia de ese año ya esta almacenada en la Base de Datos");
                jtextCodigoDeMateria.requestFocus();
            
            }else{
            
                //---Agrego una materia en el arreglo de Materias que esta en en Menu---
                Menu.getMaterias().add(new Materia(idMateria,nombreMateria,anioAlQuePertenece));
            
                //---Aviso al usuario---
                JOptionPane.showMessageDialog(this, "Registro guardado Exitosamente!!!");
                jtextCodigoDeMateria.requestFocus();
                limpiarCampos();
            
            }
        }    
    }
    
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextCodigoDeMateria = new javax.swing.JTextField();
        jtextNombreDeLaMateria = new javax.swing.JTextField();
        jbtGuardar = new javax.swing.JButton();
        jbtNuevo = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();
        jcbxAnioalQuePertenece = new javax.swing.JComboBox<>();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Formulario de Materias");

        jLabel2.setText("CODIGO DE MATERIA:");

        jLabel3.setText("NOMBRE DE LA MATERIA:");

        jLabel4.setText("AÑO AL QUE PERTENECE:");

        jtextCodigoDeMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextCodigoDeMateriaFocusLost(evt);
            }
        });
        jtextCodigoDeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextCodigoDeMateriaActionPerformed(evt);
            }
        });

        jbtGuardar.setText("Guardar");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        jbtGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtGuardarKeyPressed(evt);
            }
        });

        jbtNuevo.setText("Nuevo");
        jbtNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNuevoActionPerformed(evt);
            }
        });

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        jcbxAnioalQuePertenece.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo", "Tercero", "Cuarto", "Quinto" }));
        jcbxAnioalQuePertenece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxAnioalQuePerteneceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtextCodigoDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtextNombreDeLaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(10, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbxAnioalQuePertenece, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jbtGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextCodigoDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextNombreDeLaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbxAnioalQuePertenece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNuevo)
                    .addComponent(jbtGuardar)
                    .addComponent(jbtSalir))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jbtNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNuevoActionPerformed
        limpiarCampos();
        jtextCodigoDeMateria.requestFocus();
    }//GEN-LAST:event_jbtNuevoActionPerformed

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed
        
        registrarMateria();
     
    }//GEN-LAST:event_jbtGuardarActionPerformed

    private void jtextCodigoDeMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextCodigoDeMateriaFocusLost
        
        
        try{   //---Si no Ingreso un numero que maneje el error---
            
            int valorJText = Integer.parseInt(jtextCodigoDeMateria.getText());
            
            if (chequearSiExisteEseCodigoDeMateria(valorJText) ){
                JOptionPane.showMessageDialog(this, "El Codigo " + jtextCodigoDeMateria.getText() + "  ya esta asignado a una materia!\n\n          Ingrese uno diferente por favor ");
                jtextCodigoDeMateria.setText("");
                jtextCodigoDeMateria.requestFocus();
            }

        }catch(NumberFormatException e){

            if (!jtextCodigoDeMateria.getText().equals("")){                    //<---Si el jtextCodigoDeMateria esta vacio el campo, que No este disparando un JoptionPanee molesto al usuario
                JOptionPane.showMessageDialog(this, "El campo 'Codigo de Materias:' solo admite Numeros");
                jtextCodigoDeMateria.requestFocus();
               
                
            }
        }
        
    }//GEN-LAST:event_jtextCodigoDeMateriaFocusLost

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void jcbxAnioalQuePerteneceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxAnioalQuePerteneceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxAnioalQuePerteneceActionPerformed

    private void jtextCodigoDeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextCodigoDeMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextCodigoDeMateriaActionPerformed

    private void jbtGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtGuardarKeyPressed
        
        char c = (char) evt.getKeyCode();
        
        if(c == evt.VK_ENTER){
            
            registrarMateria();
        }
    }//GEN-LAST:event_jbtGuardarKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtNuevo;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JComboBox<String> jcbxAnioalQuePertenece;
    private javax.swing.JTextField jtextCodigoDeMateria;
    private javax.swing.JTextField jtextNombreDeLaMateria;
    // End of variables declaration//GEN-END:variables
}
