/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.Alumno;
import clases.Materia;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author AsRock
 */
public class Menu extends javax.swing.JFrame {

    //---Creo el Array static donde voy a guardar los alumnos y las Materias---
    
    private static ArrayList <Materia> materias = new ArrayList<>();
    private static ArrayList <Alumno> alumnos = new ArrayList<>();
    
    //--------------------------------------------------------------------------
       
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIconImage( new ImageIcon(getClass().getResource("/imagenes/school.png")).getImage());  
        this.setLocationRelativeTo(null);
    }
    
    //---Getter del ArrayList de Alumnos----------------------------------------
    public static ArrayList <Alumno> getAlumnos(){      
       
        return alumnos;
    } 
    
    
    //---Getter del ArrayList de Materias---------------------------------------
    public static ArrayList <Materia> getMaterias(){      
       
        return materias;
    } 
    
    //--------------------------------------------------------------------------
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/universityLoremipsum.jpg"));
        Image miImagen = icono.getImage();
        jDeskPanEscritorio = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMItemAltaDeMaterias = new javax.swing.JMenuItem();
        jMItemAltaDeAlumnos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMItemFormularioDeInscripcion = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDeskPanEscritorioLayout = new javax.swing.GroupLayout(jDeskPanEscritorio);
        jDeskPanEscritorio.setLayout(jDeskPanEscritorioLayout);
        jDeskPanEscritorioLayout.setHorizontalGroup(
            jDeskPanEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        jDeskPanEscritorioLayout.setVerticalGroup(
            jDeskPanEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        jMItemAltaDeMaterias.setText("Alta de Materias");
        jMItemAltaDeMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAltaDeMateriasActionPerformed(evt);
            }
        });
        jMenu1.add(jMItemAltaDeMaterias);

        jMItemAltaDeAlumnos.setText("Alta de Alumnos");
        jMItemAltaDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemAltaDeAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jMItemAltaDeAlumnos);
        jMenu1.add(jSeparator1);

        jMItemFormularioDeInscripcion.setText("Formulario de Inscripción");
        jMItemFormularioDeInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemFormularioDeInscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(jMItemFormularioDeInscripcion);
        jMenu1.add(jSeparator2);

        jMItemSalir.setText("Salir");
        jMItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMItemSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeskPanEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDeskPanEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemAltaDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAltaDeAlumnosActionPerformed
        jDeskPanEscritorio.removeAll();
        jDeskPanEscritorio.repaint();
        
        JIntlFrAltaDeAlumnos AltaDeAlumnos = new JIntlFrAltaDeAlumnos();
        AltaDeAlumnos.setVisible(true);
        jDeskPanEscritorio.add(AltaDeAlumnos);
    }//GEN-LAST:event_jMItemAltaDeAlumnosActionPerformed

    private void jMItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemSalirActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jMItemSalirActionPerformed

    private void jMItemAltaDeMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemAltaDeMateriasActionPerformed
        jDeskPanEscritorio.removeAll();
        jDeskPanEscritorio.repaint();
        
        JIntlFrAltaDeMaterias altaDeMaterias = new JIntlFrAltaDeMaterias();
        altaDeMaterias.setVisible(true);
        jDeskPanEscritorio.add(altaDeMaterias);
    }//GEN-LAST:event_jMItemAltaDeMateriasActionPerformed

    private void jMItemFormularioDeInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemFormularioDeInscripcionActionPerformed
        jDeskPanEscritorio.removeAll();
        jDeskPanEscritorio.repaint();
        
        JIntFrFormularioDeInscripcion formularioDeInscripcion = new JIntFrFormularioDeInscripcion();
        formularioDeInscripcion.setVisible(true);
        jDeskPanEscritorio.add(formularioDeInscripcion);
    }//GEN-LAST:event_jMItemFormularioDeInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDeskPanEscritorio;
    private javax.swing.JMenuItem jMItemAltaDeAlumnos;
    private javax.swing.JMenuItem jMItemAltaDeMaterias;
    private javax.swing.JMenuItem jMItemFormularioDeInscripcion;
    private javax.swing.JMenuItem jMItemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
